### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by wzgytuA888** [mengsig/DomiRank#1]
RuntimeError: 
An attempt has been made to start a new process before the
current process has finished its bootstrapping phase.
﻿
This probably means that you are not using fork to start your
child processes and you have forgotten to use the proper idiom
in the main module:
﻿
if __name__ == '__main__':
freeze_support()
...
﻿
The "freeze_support()" line can be omitted if the program
is not going to be frozen to produce an executable.

What is the problem with this error when running the code？

**Comment by mengsig** [comment]
Hi @wzgytuA888 

I presume you have altered the code, as I have never seen this issue before. 

Could you please send me your current script so I can try and troubleshoot? 

Is it an error that happens every-time? 

As far as I can see from the limited snippet of information I have, it seems it's a multithreading issue. Perhaps, if you run the following command: 
$ export OMP_NUM_THREADS=1
Then that will fix the issue. However, the code should be substantially slower. 

Please send me your script or more information so I can help debug. 

Best,
Marcus

**Comment by wzgytuA888** [comment]
HI @mengsig 
I have resolved the above issue. As a beginner, I defined a def main() at the beginning of the file to resolve this error. However, there is a version issue with Scipy in the future. Could you please provide a version of the library you are using in the requirements file?
Best,
wzgytu888

**Comment by mengsig** [comment]
Yes, I will do a new commit in about 30 minutes, and if everything is working for you, I will close this issue. 

Best,
Marcus

**Comment by mengsig** [comment]
Hi again @wzgytuA888 

Please find the updated version.

Please run

$ pip install -r requirements.txt

once again, and see if the version removes your deprecation errors.

If resolved, then I will close this issue, and also thank you for using my repository!

Best,
Marcus
